#!/usr/bin/env python3

"""Plot the evolution of the eccentricity envelope from pickled calculations."""

from os import path, makedirs, remove
from subprocess import call
from functools import partial

from matplotlib import pyplot, rcParams
from configargparse import\
    ArgumentParser,\
    DefaultsFormatter
import numpy
from scipy.interpolate import UnivariateSpline
from scipy.optimize import root_scalar, least_squares

from orbital_evolution.transformations import lgQ
from orbital_evolution.command_line_util import get_phase_lag_config

from .unpickle_data import unpickle_data
from .meibom_matthieu_2005_envelope import MeibomMathieuEnvelopeResidual

def parse_configuration():
    """Return the configurations of how to create the plots."""

    parser = ArgumentParser(
        description=__doc__,
        default_config_files=['envelope_plot.cfg'],
        formatter_class=DefaultsFormatter,
        ignore_unknown_config_file_keys=False
    )
    parser.add_argument(
        '--config', '-c',
        is_config_file=True,
        help='Config file to use instead of default.'
    )

    parser.add_argument(
        '--evolution-pickles', '-p',
        default=['eccentricity_envelope.pickle'],
        nargs='+',
        help='The file name(s) where the calculated evolutions are pickled. '
        'Usually generated by explore_envelope.py. Each pickle will be plotted '
        'witha defferent color.'
    )
    parser.add_argument(
        '--envelope-model',
        choices=['spline', 'mm05'],
        default='spline',
        help='How to model the period-eccentricity envelope for determining the'
        ' circularization period.'
    )
    parser.add_argument(
        '--show-interpolation',
        action='store_true',
        help='If passed, the movie showing the eccentricity envelope evolution '
        'includes lines showing the interpolation of the envelope vs period.'
    )
    parser.add_argument(
        '--frame-fname-pattern',
        default='eccentricity_envelope_frames/frame%05d.jpg',
        help='A %%-substitution pattern to generate filenames for output '
        'frames.'
    )
    parser.add_argument(
        '--envelope-movie-fname',
        default=None,
        help='Create a movie showing the evolution of the period-eccentricity '
        'enveloqe with the given filename. If empty sting, no movie is created '
        'just the individual frames which are then always preserved.'
    )
    parser.add_argument(
        '--keep-envelope-frames',
        action='store_true',
        help='If this argument is passed, the frames that were generated when '
        'creating the movie are not deleted at the end. Note that if '
        'directories are created for storing the frames they will not be '
        'automatically deleted!'
    )
    parser.add_argument(
        '--circularization-period-plot',
        default=None,
        help='Create a plot of the circularization cut-off period as a '
        'function of age with the given filename.'
    )
    parser.add_argument(
        '--circularization-threshold',
        type=float,
        default=0.1,
        help='The eccentricity threshold value uesd to determine the '
        'circularization cut-off period.'
    )
    parser.add_argument(
        '--plotting-function',
        choices=['plot', 'semilogx', 'semilogy', 'loglog'],
        default='plot',
        help='The matplotlib plotting function to use.'
    )
    parser.add_argument(
        '--label', '-l',
        default=None,
        help='A %%-substitution pattern to use as the label to display for each'
        ' set of points. All configuration entries are allowed as '
        'substitutions. Further, `%%(lgQprimary)s`" and `%%(lgQsecondary)s` can'
        ' be used, which get replated with expressions of the currently setup '
        'dissipation with all its dependencies, excluding surrounding `$`. '
        'Finally, for circularization period plots only, the label can include '
        '`%%(e0)f` which gets replaced by the initial eccentiricty a particular'
        ' envelope is based on.'
    )
    return parser.parse_args()

def get_label_substitutions(system_config):
    """Return dictionary of everything that can be included in plot labels."""

    result = vars(system_config)
    for component in ['primary', 'secondary']:
        dissipation = get_phase_lag_config(system_config,
                                           component == 'primary')
        entry = '%g' % lgQ(dissipation['reference_phase_lag'])
        if dissipation['tidal_frequency_breaks'] is not None:
            entry += ' + piecewise('
            for powerlaw_above, frequency in  zip(
                    reversed(dissipation['tidal_frequency_powers'][1:]),
                    reversed(dissipation['tidal_frequency_breaks'])
            ):
                entry += (r'%g \leftarrow P_t = %g d\rightarrow '
                          %
                          (0.0 - powerlaw_above, 2.0 * numpy.pi / frequency))
            entry += '%g)' % dissipation['tidal_frequency_powers'][0]

        if dissipation['inertial_mode_enhancement'] != 1:
            entry += (r' - %g\ \mathrm{if\ inertial}'
                      %
                      numpy.log10(dissipation['inertial_mode_enhancement']))

        result['lgQ' + component] = entry

    return result

def get_spline_envelope(data, age_index):
    """Return interpolation representing the P-e envelope at given age & ecc."""

    periods, eccentricities = data[1]

    interp_x = periods[age_index, :, -1]
    interp_y = eccentricities[age_index, :, -1]
    good_data = numpy.logical_and(
        numpy.isfinite(interp_x),
        numpy.isfinite(interp_y)
    )
    interp_x = interp_x[good_data]
    interp_y = interp_y[good_data]
    sorting_indices = numpy.argsort(interp_x)
    interp_x = interp_x[sorting_indices]
    interp_y = interp_y[sorting_indices]
    result = UnivariateSpline(interp_x,
                              interp_y,
                              s=1e-6 * interp_y.size)
    result.support = interp_x[0], interp_x[-1]
    return result

def get_mm05_envelope(data, age_index):
    """Return best fit Meibom & Matthieu 05 model of the given P-e envelope."""

    def simulated_period(eccentricity):
        """Return the period at which the simulated envelope exceeds given e."""

        return data[1][0][numpy.searchsorted(data[1][1], eccentricity)]

    max_fit_e = data[0].eccentricity_grid[-1] - 0.2
    pcirc_guess = simulated_period(0.025)
    alpha_guess = 1.0
    beta_guess = (numpy.log(1.0 - max_fit_e)
                  /
                  (pcirc_guess - simulated_period(max_fit_e)))
    gamma_guess = 1.0

    calc_residuals = MeibomMathieuEnvelopeResidual([data],
                                                   (0.05, max_fit_e),
                                                   age_index)
    fit_result = least_squares(
        calc_residuals,
        [pcirc_guess, alpha_guess, beta_guess, gamma_guess]
    )
    assert fit_result.success
    return partial(calc_residuals.max_eccentricity,
                   model_parameters=fit_result.x,
                   sim_config=data[0])

def find_circularization_period(data, threshold, get_envelope):
    """
    Estimate the period where the eccentricity envelope crosses a threshold.

    Args:
        data:    The pickled evolution data.

        threshold:    The threshold eccentricity we are trying to estimate the
            crossing of.

        get_envelope:    One of the function that defines a period-eccentricity
            envelope given data and age index.

    Returns:
        2-D array:
            The largest orbital period below which all systems at a given age
            starting with the same initial eccentricity should have
            eccentricities below threshold. The first index is over initial
            eccentricity and the second index is over age.
    """

    config = data[0]
    result = numpy.full(
        shape=(config.plot_ages.size,),
        dtype=numpy.float64,
        fill_value=numpy.nan
    )
    for age_index in range(config.plot_ages.size):
        envelope = get_envelope(data, age_index)
        try:
            root_find_result = root_scalar(
                #pylint: disable=cell-var-from-loop
                lambda x: envelope(x) - threshold,
                #pylint: enable=cell-var-from-loop
                bracket=envelope.support,
                fprime=envelope.derivative(),
                fprime2=envelope.derivative(2)
            )
            assert root_find_result.converged
            result[age_index] = root_find_result.root
        except ValueError:
            pass

    return result

def create_movie(frame_pattern, movie_fname):
    """Stitch the generated frames into a movie."""

    call(['ffmpeg',
          '-f', 'image2',
          '-framerate', '10',
          '-i', frame_pattern,
          movie_fname])

#No goodway to simplify
#pylint: disable=too-many-locals
def plot_frame(frame, data, get_envelope, config):
    """Setup a plot to save as a single frame of the circularization movie."""

    plot_colors = ['#1f78b4',
                   '#e31a1c',
                   '#33a02c',
                   '#ff7f00',
                   '#6a3d9a',
                   '#a6cee3',
                   '#fb9a99',
                   '#b2df8a',
                   '#fdbf6f',
                   '#cab2d6']

    plot = getattr(pyplot, config.plotting_function)

    xmax = ymax = -numpy.inf
    xmin = numpy.inf
    color_index = 0
    for single_run_data in data:
        scenario_config, _ = single_run_data
        xmax = max(scenario_config.orbital_period_grid[-1], xmax)
        ymax = max(scenario_config.eccentricity_grid[-1], ymax)
        xmin = min(scenario_config.orbital_period_grid[0], xmin)


        for eccentricity_index, initial_eccentricity in enumerate(
                single_run_data[0].eccentricity_grid
        ):
            color = plot_colors[color_index % len(plot_colors)]
            plot_config = dict(markeredgecolor=color,
                               markerfacecolor=color)
            color_index += 1

            if config.label is not None:
                plot_config['label'] = config.label % dict(
                    get_label_substitutions(scenario_config),
                    e0=initial_eccentricity
                )
            plot(single_run_data[1][0][frame, :, eccentricity_index],
                 single_run_data[1][1][frame, :, eccentricity_index],
                 'o',
                 **plot_config)
        if config.show_interpolation:
            eval_x = numpy.linspace(0, xmax, 1000)
            plot(
                eval_x,
                get_envelope(single_run_data, frame)(eval_x),
                '-',
                color=color
            )

    if config.plotting_function in ['plot', 'semilogy']:
        pyplot.xlim(0, xmax)
    else:
        pyplot.xlim(xmin, xmax)
    if config.plotting_function in ['plot', 'semilogx']:
        pyplot.ylim(0, ymax)
    else:
        pyplot.ylim(1e-3, ymax)
    pyplot.figlegend(loc=2)
#pylint: enable=too-many-locals

def main(config):
    """Avoid polluting global namespace."""

    frame_fnames = []
    data = [unpickle_data(evolution_pickle)
            for evolution_pickle in config.evolution_pickles]
    plot_ages = data[0][0].plot_ages
    for scenario_config, _ in data:
        assert (scenario_config.plot_ages == plot_ages).all()

    get_envelope = globals()['get_%s_envelope' % config.envelope_model]


    if config.frame_fname_pattern:
        for frame, age in enumerate(plot_ages):
            plot_frame(frame, data, get_envelope, config)
            pyplot.title('Age = %.3f' % age)

            outfname = config.frame_fname_pattern % frame
            outdir = path.dirname(outfname)
            if outdir and not path.exists(outdir):
                makedirs(outdir)
            pyplot.savefig(outfname)
            pyplot.cla()
            frame_fnames.append(outfname)

            print('Envelope movie progress: %s%%'
                  %
                  (100.0 * frame / plot_ages.size),
                  end='\r')

        if config.envelope_movie_fname:
            create_movie(config.frame_fname_pattern,
                         config.envelope_movie_fname)
            if not config.keep_envelope_frames:
                for oufname in frame_fnames:
                    remove(oufname)

    if config.circularization_period_plot:
        plot_config = dict(linestyle='-')
        for scenario_data in data:
            circularization_period = find_circularization_period(
                scenario_data,
                config.circularization_threshold,
                get_envelope
            )
            if config.label is not None:
                plot_config['label'] = config.label % dict(
                    get_label_substitutions(
                        scenario_data[0]
                    ),
                    e0=scenario_data[0].eccentricity_grid[-1]
                )

            getattr(pyplot, config.plotting_function)(
                scenario_data[0].plot_ages,
                circularization_period,
                **plot_config
            )
        pyplot.figlegend(loc=2)
        pyplot.savefig(config.circularization_period_plot)
        pyplot.cla()

if __name__ == '__main__':
    rcParams['figure.figsize'] = [6.4, 9.6]
    rcParams['figure.subplot.top'] = 0.5
    main(parse_configuration())
