#!/usr/bin/env python3

"""Plot the evolution of the eccentricity envelope from pickled calculations."""

from os import path, makedirs, remove
from subprocess import call
from functools import partial

from matplotlib import pyplot, rcParams
from configargparse import\
    ArgumentParser,\
    DefaultsFormatter
import numpy
from scipy.interpolate import UnivariateSpline
from scipy.optimize import root_scalar, minimize

from orbital_evolution.transformations import lgQ
from orbital_evolution.command_line_util import get_phase_lag_config

from period_eccentricity_envelope.unpickle_data import unpickle_data
from period_eccentricity_envelope.mm05_envelope import MM05EnvelopeResidual

def parse_configuration():
    """Return the configurations of how to create the plots."""

    parser = ArgumentParser(
        description=__doc__,
        default_config_files=['envelope_plot.cfg'],
        formatter_class=DefaultsFormatter,
        ignore_unknown_config_file_keys=False
    )
    parser.add_argument(
        '--config', '-c',
        is_config_file=True,
        help='Config file to use instead of default.'
    )

    parser.add_argument(
        '--evolution-pickles', '-p',
        default=['eccentricity_envelope.pickle'],
        nargs='+',
        help='The file name(s) where the calculated evolutions are pickled. '
        'Usually generated by explore_envelope.py. Each pickle will be plotted '
        'witha defferent color.'
    )
    parser.add_argument(
        '--envelope-model',
        choices=['spline', 'mm05'],
        default='spline',
        help='How to model the period-eccentricity envelope for determining the'
        ' circularization period.'
    )
    parser.add_argument(
        '--show-interpolation',
        action='store_true',
        help='If passed, the movie showing the eccentricity envelope evolution '
        'includes lines showing the interpolation of the envelope vs period.'
    )
    parser.add_argument(
        '--frame-fname-pattern',
        default='eccentricity_envelope_frames/frame%05d.jpg',
        help='A %%-substitution pattern to generate filenames for output '
        'frames.'
    )
    parser.add_argument(
        '--envelope-movie-fname',
        default=None,
        help='Create a movie showing the evolution of the period-eccentricity '
        'enveloqe with the given filename. If empty sting, no movie is created '
        'just the individual frames which are then always preserved.'
    )
    parser.add_argument(
        '--keep-envelope-frames',
        action='store_true',
        help='If this argument is passed, the frames that were generated when '
        'creating the movie are not deleted at the end. Note that if '
        'directories are created for storing the frames they will not be '
        'automatically deleted!'
    )
    parser.add_argument(
        '--model-evolution-plot',
        default=None,
        help='Create figure with plots of the circularization cut-off period '
        'and the best fit parameters of the period eccentricity envelope as a '
        'function of age. Save to a file with the given filename.'
    )
    parser.add_argument(
        '--circularization-threshold',
        type=float,
        default=0.1,
        help='The eccentricity threshold value uesd to determine the '
        'circularization cut-off period.'
    )
    parser.add_argument(
        '--plotting-function',
        choices=['plot', 'semilogx', 'semilogy', 'loglog'],
        default='plot',
        help='The matplotlib plotting function to use.'
    )
    parser.add_argument(
        '--label', '-l',
        default=None,
        help='A %%-substitution pattern to use as the label to display for each'
        ' set of points. All configuration entries are allowed as '
        'substitutions. Further, `%%(lgQprimary)s`" and `%%(lgQsecondary)s` can'
        ' be used, which get replated with expressions of the currently setup '
        'dissipation with all its dependencies, excluding surrounding `$`. '
        'Finally, for circularization period plots only, the label can include '
        '`%%(e0)f` which gets replaced by the initial eccentiricty a particular'
        ' envelope is based on.'
    )
    return parser.parse_args()

def get_label_substitutions(system_config):
    """Return dictionary of everything that can be included in plot labels."""

    result = vars(system_config)
    for component in ['primary', 'secondary']:
        dissipation = get_phase_lag_config(system_config,
                                           component == 'primary')
        entry = '%g' % lgQ(dissipation['reference_phase_lag'])
        if dissipation['tidal_frequency_breaks'] is not None:
            entry += ' + piecewise('
            for powerlaw_above, frequency in  zip(
                    reversed(dissipation['tidal_frequency_powers'][1:]),
                    reversed(dissipation['tidal_frequency_breaks'])
            ):
                entry += (r'%g \leftarrow P_t = %g d\rightarrow '
                          %
                          (0.0 - powerlaw_above, 2.0 * numpy.pi / frequency))
            entry += '%g)' % dissipation['tidal_frequency_powers'][0]

        if dissipation['inertial_mode_enhancement'] != 1:
            entry += (r' - %g\ \mathrm{if\ inertial}'
                      %
                      numpy.log10(dissipation['inertial_mode_enhancement']))

        result['lgQ' + component] = entry

    return result

def get_spline_envelope(data, age_index):
    """Return interpolation representing the P-e envelope at given age & ecc."""

    periods, eccentricities = data[1]

    interp_x = periods[age_index, :, -1]
    interp_y = eccentricities[age_index, :, -1]
    good_data = numpy.logical_and(
        numpy.isfinite(interp_x),
        numpy.isfinite(interp_y)
    )
    interp_x = interp_x[good_data]
    interp_y = interp_y[good_data]
    sorting_indices = numpy.argsort(interp_x)
    interp_x = interp_x[sorting_indices]
    interp_y = interp_y[sorting_indices]
    result = UnivariateSpline(interp_x,
                              interp_y,
                              s=1e-6 * interp_y.size)
    result.support = interp_x[0], interp_x[-1]
    return result, None

def get_mm05_envelope(data, age_index):
    """Return best fit Meibom & Matthieu 05 model of the given P-e envelope."""

    def simulated_period(eccentricity):
        """Return the period at which the simulated envelope exceeds given e."""

        sim_periods = data[1][0][age_index, :, -1]
        sim_eccentricities = data[1][1][age_index, :, -1]
        finite = numpy.isfinite(sim_periods)
        if not finite.any():
            return numpy.nan
        sim_peridos = sim_periods[finite]
        sim_eccentricities = sim_eccentricities[finite]
        crossing_index = int(
            numpy.searchsorted(sim_eccentricities, eccentricity)
        )
        if crossing_index == sim_eccentricities.size:
            crossing_index -= 1
        return sim_peridos[crossing_index]

    max_fit_e = data[0].eccentricity_grid[-1] - 0.2
    pcirc_guess = simulated_period(0.025)
    beta_guess = (numpy.log(1.0 - max_fit_e)
                  /
                  (pcirc_guess - simulated_period(max_fit_e)))
    gamma_guess = 1.0
    parameter_guess = [pcirc_guess, beta_guess, gamma_guess]

    calc_residuals = MM05EnvelopeResidual([data],
                                          (0.05, max_fit_e),
                                          age_index)
    if not numpy.isfinite(calc_residuals(parameter_guess)):
        return None, None

    fit_result = minimize(calc_residuals, parameter_guess)
    if not fit_result.success:
        return None, None
    envelope_function = partial(calc_residuals.max_eccentricity,
                                model_parameters=fit_result.x,
                                sim_config=data[0])
    envelope_function.support=(fit_result.x[0],
                               fit_result.x[0] + 1.0 / fit_result.x[1])
    return (
        envelope_function,
        fit_result.x
    )

def get_model_evolution(data, threshold, get_envelope):
    """
    Estimate the period where the eccentricity envelope crosses a threshold.

    Args:
        data:    The pickled evolution data.

        threshold:    The threshold eccentricity we are trying to estimate the
            crossing of.

        get_envelope:    One of the function that defines a period-eccentricity
            envelope given data and age index.

    Returns:
        2-D array with the following columns:

            0. The largest orbital period below which all systems at a given age
               starting with the same initial eccentricity should have
               eccentricities below threshold. The first index is over initial
               eccentricity and the second index is over age.

            1. The best fit value of the first model parameter

            2. The best fit value of the second model parameter

            ...
    """

    config = data[0]
    result = None
    for age_index in range(config.plot_ages.size):
        envelope, parameters = get_envelope(data, age_index)
        if envelope is None:
            continue
        if result is None:
            result = numpy.full(
                shape=(parameters.size + 1, config.plot_ages.size),
                dtype=numpy.float64,
                fill_value=numpy.nan
            )
        result[1:, age_index] = parameters
        try:
            extra_args = dict()
            if hasattr(envelope, 'derivative'):
                extra_args['fprime'] = envelope.derivative()
                extra_args['fprime2'] = envelope.derivative(2)
            root_find_result = root_scalar(
                #pylint: disable=cell-var-from-loop
                lambda x: envelope(x) - threshold,
                #pylint: enable=cell-var-from-loop
                bracket=envelope.support,
                **extra_args
            )
            assert root_find_result.converged
            result[0, age_index] = root_find_result.root
        except ValueError:
            pass

    return result

def create_movie(frame_pattern, movie_fname):
    """Stitch the generated frames into a movie."""

    call(['ffmpeg',
          '-f', 'image2',
          '-framerate', '10',
          '-i', frame_pattern,
          movie_fname])

#No goodway to simplify
#pylint: disable=too-many-locals
def plot_frame(frame, data, get_envelope, config):
    """Setup a plot to save as a single frame of the circularization movie."""

    plot_colors = ['#1f78b4',
                   '#e31a1c',
                   '#33a02c',
                   '#ff7f00',
                   '#6a3d9a',
                   '#a6cee3',
                   '#fb9a99',
                   '#b2df8a',
                   '#fdbf6f',
                   '#cab2d6']

    plot = getattr(pyplot, config.plotting_function)

    xmax = ymax = -numpy.inf
    xmin = numpy.inf
    color_index = 0
    for single_run_data in data:
        scenario_config, _ = single_run_data
        xmax = max(scenario_config.orbital_period_grid[-1], xmax)
        ymax = max(scenario_config.eccentricity_grid[-1], ymax)
        xmin = min(scenario_config.orbital_period_grid[0], xmin)


        for eccentricity_index, initial_eccentricity in enumerate(
                single_run_data[0].eccentricity_grid
        ):
            color = plot_colors[color_index % len(plot_colors)]
            plot_config = dict(markeredgecolor=color,
                               markerfacecolor=color)
            color_index += 1

            if config.label is not None:
                plot_config['label'] = config.label % dict(
                    get_label_substitutions(scenario_config),
                    e0=initial_eccentricity
                )
            plot(single_run_data[1][0][frame, :, eccentricity_index],
                 single_run_data[1][1][frame, :, eccentricity_index],
                 'o',
                 **plot_config)
        if config.show_interpolation:
            eval_x = numpy.linspace(0, xmax, 1000)
            envelope = get_envelope(single_run_data, frame)[0]
            if envelope is not None:
                plot(eval_x, envelope(eval_x), '-', color=color)

    if config.plotting_function in ['plot', 'semilogy']:
        pyplot.xlim(0, xmax)
    else:
        pyplot.xlim(xmin, xmax)
    if config.plotting_function in ['plot', 'semilogx']:
        pyplot.ylim(0, ymax)
    else:
        pyplot.ylim(1e-3, ymax)
    pyplot.figlegend(loc=2)
#pylint: enable=too-many-locals

def create_envelope_movie(data, plot_ages, get_envelope, config):
    """Create the movie showing the simulated envelope evolution."""

    frame_fnames = []
    for frame, age in enumerate(plot_ages):
        plot_frame(frame, data, get_envelope, config)
        pyplot.title('Age = %.3f' % age)

        outfname = config.frame_fname_pattern % frame
        outdir = path.dirname(outfname)
        if outdir and not path.exists(outdir):
            makedirs(outdir)
        pyplot.savefig(outfname)
        pyplot.cla()
        frame_fnames.append(outfname)

        print('Envelope movie progress: %s%%'
              %
              (100.0 * frame / plot_ages.size),
              end='\r')

    if config.envelope_movie_fname:
        create_movie(config.frame_fname_pattern,
                     config.envelope_movie_fname)
        if not config.keep_envelope_frames:
            for oufname in frame_fnames:
                remove(oufname)

def create_model_evolution_figure(data, plot_ages, get_envelope, config):
    """Craete the figure with plots of the evolution of P-e model parameters."""

    plot_config = dict(linestyle='-')
    plot_axes = None
    print('%25s %25s %25s %25s %25s %25s'
          %
          ('M1', 'M2', 'Pthresh', 'Pcirc', 'beta', 'gamma'))
    ngc188_age_index = numpy.searchsorted(plot_ages, 7.0)
    if plot_ages[ngc188_age_index - 1] < plot_ages[ngc188_age_index]:
        ngc188_age_index -= 1
    for scenario_data in data:
        model_evolution = get_model_evolution(
            scenario_data,
            config.circularization_threshold,
            get_envelope
        )
        print(
            '%25.16e %25.16e %25.16e %25.16e %25.16e %25.16e'
            %
            (
                (
                    scenario_data[0].primary_mass,
                    scenario_data[0].secondary_mass
                )
                +
                tuple(model_evolution[:, ngc188_age_index])
            )
        )
        if plot_axes is None:
            plot_axes = pyplot.subplots(
                model_evolution.shape[0],
                figsize=(6.4, 4.8 * (model_evolution.shape[0] + 1))
            )[1]
        if config.label is not None:
            plot_config['label'] = config.label % dict(
                get_label_substitutions(
                    scenario_data[0]
                ),
                e0=scenario_data[0].eccentricity_grid[-1]
            )

        for destination, evolution in zip(plot_axes, model_evolution):
            getattr(destination, config.plotting_function)(
                plot_ages,
                evolution,
                **plot_config
            )
    pyplot.figlegend(loc=2)
    pyplot.savefig(config.model_evolution_plot)
    pyplot.cla()

def main(config):
    """Avoid polluting global namespace."""

    data = [unpickle_data(evolution_pickle)
            for evolution_pickle in config.evolution_pickles]
    plot_ages = data[0][0].plot_ages
    for scenario_config, _ in data:
        assert (scenario_config.plot_ages == plot_ages).all()

    get_envelope = globals()['get_%s_envelope' % config.envelope_model]


    if config.frame_fname_pattern:
        create_envelope_movie(data,
                              plot_ages,
                              get_envelope,
                              config)
    if config.model_evolution_plot:
        create_model_evolution_figure(data,
                                      plot_ages,
                                      get_envelope,
                                      config)
if __name__ == '__main__':
    rcParams['figure.figsize'] = [6.4, 9.6]
    rcParams['figure.subplot.top'] = 0.5
    main(parse_configuration())
