#!/usr/bin/env python3

"""Plot the evolution of the eccentricity envelope from pickled calculations."""

import pickle
from os import path, makedirs, remove
from subprocess import call

from matplotlib import pyplot
from configargparse import\
    ArgumentParser,\
    DefaultsFormatter
import numpy
from scipy.interpolate import UnivariateSpline
from scipy.optimize import root_scalar

from orbital_evolution.transformations import lgQ
from orbital_evolution.command_line_util import get_phase_lag_config

def parse_configuration():
    """Return the configurations of how to create the plots."""

    parser = ArgumentParser(
        description=__doc__,
        default_config_files=['envelope_plot.cfg'],
        formatter_class=DefaultsFormatter,
        ignore_unknown_config_file_keys=False
    )
    parser.add_argument(
        '--config', '-c',
        is_config_file=True,
        help='Config file to use instead of default.'
    )

    parser.add_argument(
        '--evolution-pickles', '-p',
        default=['eccentricity_envelope.pickle'],
        nargs='+',
        help='The file name(s) where the calculated evolutions are pickled. '
        'Usually generated by explore_envelope.py. Each pickle will be plotted '
        'witha defferent color.'
    )
    parser.add_argument(
        '--show-interpolation',
        action='store_true',
        help='If passed, the movie showing the eccentricity envelope evolution '
        'includes lines showing the interpolation of the envelope vs period.'
    )
    parser.add_argument(
        '--frame-fname-pattern',
        default='eccentricity_envelope_frames/frame%05d.jpg',
        help='A %%-substitution pattern to generate filenames for output '
        'frames.'
    )
    parser.add_argument(
        '--envelope-movie-fname',
        default=None,
        help='Create a movie showing the evolution of the period-eccentricity '
        'enveloqe with the given filename. If empty sting, no movie is created '
        'just the individual frames which are then always preserved.'
    )
    parser.add_argument(
        '--keep-envelope-frames',
        action='store_true',
        help='If this argument is passed, the frames that were generated when '
        'creating the movie are not deleted at the end. Note that if '
        'directories are created for storing the frames they will not be '
        'automatically deleted!'
    )
    parser.add_argument(
        '--circularization-period-plot',
        default=None,
        help='Create a plot of the circularization cut-off period as a '
        'function of age with the given filename.'
    )
    parser.add_argument(
        '--circularization-threshold',
        type=float,
        default=0.1,
        help='The eccentricity threshold value uesd to determine the '
        'circularization cut-off period.'
    )
    parser.add_argument(
        '--label', '-l',
        default=None,
        help='A %%-substitution pattern to use as the label to display for each'
        ' set of points. All configuration entries are allowed as '
        'substitutions. Further, `%%(lgQprimary)s`" and `%%(lgQsecondary)s` can'
        ' be used, which get replated with expressions of the currently setup '
        'dissipation with all its dependencies, excluding surrounding `$`. '
        'Finally, for circularization period plots only, the label can include '
        '`%%(e0)f` which gets replaced by the initial eccentiricty a particular'
        ' envelope is based on.'
    )
    return parser.parse_args()

def unpickle_data(pickle_fname):
    """Return the pickled data to plot from the given file."""

    with open(pickle_fname, 'rb') as pickle_file:
        pickled_config = pickle.load(pickle_file)
        period_evolutions = numpy.full(
            shape=(pickled_config.plot_ages.size,
                   pickled_config.orbital_period_grid.size,
                   pickled_config.eccentricity_grid.size),
            fill_value=numpy.nan,
            dtype=numpy.float64
        )
        eccentricity_evolutions = numpy.full(
            shape=period_evolutions.shape,
            fill_value=numpy.nan,
            dtype=numpy.float64
        )

        try:
            while True:
                period_index = pickled_config.orbital_period_grid.searchsorted(
                    pickle.load(pickle_file)
                )
                ecc_index = pickled_config.eccentricity_grid.searchsorted(
                    pickle.load(pickle_file)
                )
                evolution = pickle.load(pickle_file)
                num_steps = evolution.age.size
                if not (
                        numpy.abs(pickled_config.plot_ages[:num_steps]
                                  -
                                  evolution.age)
                        <
                        1e-10
                ).all():
                    continue
                period_evolutions[:num_steps, period_index, ecc_index] = (
                    evolution.orbital_period
                )
                eccentricity_evolutions[:num_steps, period_index, ecc_index] = (
                    evolution.eccentricity
                )
        except EOFError:
            pass

    return (
        pickled_config,
        (
            period_evolutions,
            eccentricity_evolutions
        )
    )

def get_label_substitutions(system_config):
    """Return dictionary of everything that can be included in plot labels."""

    result = vars(system_config)
    for component in ['primary', 'secondary']:
        dissipation = get_phase_lag_config(system_config,
                                           component == 'primary')
        entry = '%g' % lgQ(dissipation['reference_phase_lag'])
        if dissipation['tidal_frequency_breaks'] is not None:
            entry += ' + piecewise('
            for powerlaw_above, frequency in  zip(
                    reversed(dissipation['tidal_frequency_powers'][1:]),
                    reversed(dissipation['tidal_frequency_breaks'])
            ):
                entry += (r'%g \leftarrow P_{tide} = %g d\rightarrow '
                          %
                          (0.0 - powerlaw_above, 2.0 * numpy.pi / frequency))
            entry += '%g)' % dissipation['tidal_frequency_powers'][0]

        if dissipation['inertial_mode_enhancement'] != 1:
            entry += (r' - %g\ \mathrm{if\ inertial}'
                      %
                      numpy.log10(dissipation['inertial_mode_enhancement']))

        result['lgQ' + component] = entry

    return result

def interpolate_envelope(data, eccentricity_index, age_index):
    """Return interpolation representing the P-e envelope at given age & ecc."""

    periods, eccentricities = data[1]

    interp_x = periods[age_index, :, eccentricity_index]
    interp_y = eccentricities[age_index, :, eccentricity_index]
    good_data = numpy.logical_and(
        numpy.isfinite(interp_x),
        numpy.isfinite(interp_y)
    )
    interp_x = interp_x[good_data]
    interp_y = interp_y[good_data]
    sorting_indices = numpy.argsort(interp_x)
    interp_x = interp_x[sorting_indices]
    interp_y = interp_y[sorting_indices]
    result = UnivariateSpline(interp_x,
                              interp_y,
                              s=1e-6 * interp_y.size)
    result.support = interp_x[0], interp_x[-1]
    return result

def find_circularization_period(data, threshold):
    """
    Estimate the period where the eccentricity envelope crosses a threshold.

    Args:
        data:    The pickled evolution data.

        threshold:    The threshold eccentricity we are trying to estimate the
            crossing of.

    Returns:
        2-D array:
            The largest orbital period below which all systems at a given age
            starting with the same initial eccentricity should have
            eccentricities below threshold. The first index is over initial
            eccentricity and the second index is over age.
    """

    config = data[0]
    result = numpy.full(
        shape=(config.eccentricity_grid.size, config.plot_ages.size),
        dtype=numpy.float64,
        fill_value=numpy.nan
    )
    for eccentricity_index in range(config.eccentricity_grid.size):
        for age_index in range(config.plot_ages.size):
            envelope = interpolate_envelope(data, eccentricity_index, age_index)
            try:
                root_find_result = root_scalar(
                    #pylint: disable=cell-var-from-loop
                    lambda x: envelope(x) - threshold,
                    #pylint: enable=cell-var-from-loop
                    bracket=envelope.support,
                    fprime=envelope.derivative(),
                    fprime2=envelope.derivative(2)
                )
                assert root_find_result.converged
                result[eccentricity_index, age_index] = root_find_result.root
            except ValueError:
                pass

    return result

def create_movie(frame_pattern, movie_fname):
    """Stitch the generated frames into a movie."""

    call(['ffmpeg',
          '-f', 'image2',
          '-framerate', '10',
          '-i', frame_pattern,
          movie_fname])

def plot_frame(frame, data, label, show_interpolation):
    """Setup a plot to save as a single frame of the circularization movie."""

    plot_colors = ['#e41a1c',
                   '#377eb8',
                   '#4daf4a',
                   '#984ea3',
                   '#ff7f00']

    xmax = ymax = -numpy.inf
    for color_index, single_run_data in enumerate(data):

        scenario_config, _ = single_run_data
        color = plot_colors[color_index % len(plot_colors)]
        plot_config = dict(markeredgecolor=color,
                           markerfacecolor=color)
        if label is not None:
            plot_config['label'] = label % get_label_substitutions(
                scenario_config
            )
        pyplot.plot(single_run_data[1][0][frame].flatten(),
                    single_run_data[1][1][frame].flatten(),
                    'o',
                    **plot_config)
        xmax = max(scenario_config.orbital_period_grid[-1], xmax)
        ymax = max(scenario_config.eccentricity_grid[-1], ymax)
        if show_interpolation:
            eval_x = numpy.linspace(0, xmax, 1000)
            for eccentricity_index in range(
                    scenario_config.eccentricity_grid.size
            ):
                pyplot.plot(
                    eval_x,
                    interpolate_envelope(single_run_data,
                                         eccentricity_index,
                                         frame)(eval_x),
                    '-',
                    color=color
                )

    pyplot.xlim(0, xmax)
    pyplot.ylim(0, ymax)
    pyplot.legend(loc=2)

def main(config):
    """Avoid polluting global namespace."""

    frame_fnames = []
    data = [unpickle_data(evolution_pickle)
            for evolution_pickle in config.evolution_pickles]
    plot_ages = data[0][0].plot_ages
    for scenario_config, _ in data:
        assert (scenario_config.plot_ages == plot_ages).all()


    if config.frame_fname_pattern:
        for frame, age in enumerate(plot_ages):
            plot_frame(frame, data, config.label, config.show_interpolation)
            pyplot.title('Age = %.3f' % age)

            outfname = config.frame_fname_pattern % frame
            outdir = path.dirname(outfname)
            if outdir and not path.exists(outdir):
                makedirs(outdir)
            pyplot.savefig(outfname)
            pyplot.cla()
            frame_fnames.append(outfname)

        if config.envelope_movie_fname:
            create_movie(config.frame_fname_pattern,
                         config.envelope_movie_fname)
            if not config.keep_envelope_frames:
                for oufname in frame_fnames:
                    remove(oufname)

    if config.circularization_period_plot:
        plot_config = dict(linestyle='-')
        for scenario_data in data:
            circularization_period = find_circularization_period(
                scenario_data,
                config.circularization_threshold
            )
            for eccentricity_index, initial_eccentricity in enumerate(
                    scenario_data[0].eccentricity_grid
            ):
                if config.label is not None:
                    plot_config['label'] = config.label % dict(
                        get_label_substitutions(
                            scenario_data[0]
                        ),
                        e0=initial_eccentricity
                    )

                pyplot.plot(
                    scenario_data[0].plot_ages,
                    circularization_period[eccentricity_index],
                    **plot_config
                )
        pyplot.legend(loc=2)
        pyplot.savefig(config.circularization_period_plot)
        pyplot.cla()

if __name__ == '__main__':
    main(parse_configuration())
