#!/usr/bin/env python3

"""Plot the evolution of the eccentricity envelope from pickled calculations."""

import pickle
from os import path, makedirs, remove
from subprocess import call

from matplotlib import pyplot
from configargparse import\
    ArgumentParser,\
    DefaultsFormatter
import numpy

def parse_configuration():
    """Return the configurations of how to create the plots."""

    parser = ArgumentParser(
        description=__doc__,
        default_config_files=['envelope_plot.cfg'],
        formatter_class=DefaultsFormatter,
        ignore_unknown_config_file_keys=False
    )
    parser.add_argument(
        '--config', '-c',
        is_config_file=True,
        help='Config file to use instead of default.'
    )

    parser.add_argument(
        '--evolution-pickles', '-p',
        default=['eccentricity_envelope.pickle'],
        nargs='+',
        help='The file name(s) where the calculated evolutions are pickled. '
        'Usually generated by explore_envelope.py. Each pickle will be plotted '
        'witha defferent color.'
    )
    parser.add_argument(
        '--frame-fname-pattern',
        default='eccentricity_envelope_frames/frame%05d.jpg',
        help='A %%-substitution pattern to generate filenames for output '
        'frames.'
    )
    parser.add_argument(
        '--movie-fname',
        default='eccentricity_envelope_evolution.mp4',
        help='A filename to save the movie as. If empty sting, no movie is '
        'created just tho individual frames which are then always preserved.'
    )
    parser.add_argument(
        '--keep-frames',
        action='store_true',
        help='If this argument is passed, the frames that were generated when '
        'creating the movie are not deleted at the end. Note that if '
        'directories are created for storing the frames they will not be '
        'automatically deleted!'
    )
    parser.add_argument(
        '--label', '-l',
        default=None,
        help='A %%-substitution pattern involving configuration entries from '
        'the pickles to use as the label to display for each set of points.'
    )

    return parser.parse_args()

def unpickle_data(pickle_fname):
    """Return the pickled data to plot from the given file."""

    with open(pickle_fname, 'rb') as pickle_file:
        pickled_config = pickle.load(pickle_file)
        period_evolutions = numpy.full(
            shape=(pickled_config.plot_ages.size,
                   pickled_config.orbital_period_grid.size,
                   pickled_config.eccentricity_grid.size),
            fill_value=numpy.nan,
            dtype=numpy.float64
        )
        eccentricity_evolutions = numpy.full(
            shape=period_evolutions.shape,
            fill_value=numpy.nan,
            dtype=numpy.float64
        )

        try:
            while True:
                period_index = pickled_config.orbital_period_grid.searchsorted(
                    pickle.load(pickle_file)
                )
                ecc_index = pickled_config.eccentricity_grid.searchsorted(
                    pickle.load(pickle_file)
                )
                evolution = pickle.load(pickle_file)
                num_steps = evolution.age.size
                print(
                    'Comparing:\n%s\nto\n%s'
                    %
                    (
                        repr(pickled_config.plot_ages[:num_steps]),
                        repr(evolution.age)
                    )
                )
                if not (
                        numpy.abs(pickled_config.plot_ages[:num_steps]
                                  -
                                  evolution.age)
                        <
                        1e-10
                ).all():
                    continue
                period_evolutions[:num_steps, period_index, ecc_index] = (
                    evolution.orbital_period
                )
                eccentricity_evolutions[:num_steps, period_index, ecc_index] = (
                    evolution.eccentricity
                )
        except EOFError:
            pass

    return (
        pickled_config,
        (
            period_evolutions,
            eccentricity_evolutions
        )
    )

def create_movie(frame_pattern, movie_fname):
    """Stitch the generated frames into a movie."""

    call(['ffmpeg',
          '-f', 'image2',
          '-framerate', '10',
          '-i', frame_pattern,
          movie_fname])

if __name__ == '__main__':
    config = parse_configuration()
    frame_fnames = []
    plot_colors = ['#e41a1c',
                   '#377eb8',
                   '#4daf4a',
                   '#984ea3',
                   '#ff7f00']
    data = [unpickle_data(evolution_pickle)
            for evolution_pickle in config.evolution_pickles]
    plot_ages = data[0][0].plot_ages
    for system_config, system_data in data:
        assert (system_config.plot_ages == plot_ages).all()

    for frame, age in enumerate(plot_ages):
        xmin, xmax, ymin, ymax = numpy.inf, -numpy.inf, numpy.inf, -numpy.inf
        for (
                color_index,
                (
                    system_config,
                    (periods, eccentricities)
                )
        ) in enumerate(data):
            color = plot_colors[color_index % len(plot_colors)]
            plot_config = dict(markeredgecolor=color,
                               markerfacecolor=color)
            if config.label is not None:
                plot_config['label'] = config.label % vars(system_config)
            pyplot.plot(periods[frame].flatten(),
                        eccentricities[frame].flatten(),
                        'o',
                        **plot_config)
            xmin = min(system_config.orbital_period_grid[0], xmin)
            xmax = max(system_config.orbital_period_grid[-1], xmax)
            ymin = min(system_config.eccentricity_grid[0], ymin)
            ymax = max(system_config.eccentricity_grid[-1], ymax)

        pyplot.xlim(xmin, xmax)
        pyplot.ylim(ymin, ymax)
        pyplot.legend(loc=2)
        pyplot.title('Age = %.3f' % age)
        outfname = config.frame_fname_pattern % frame
        outdir = path.dirname(outfname)
        if outdir and not path.exists(outdir):
            makedirs(outdir)
        pyplot.savefig(outfname)
        pyplot.cla()
        frame_fnames.append(outfname)

    if config.movie_fname:
        create_movie(config.frame_fname_pattern, config.movie_fname)
        if not config.keep_frames:
            for oufname in frame_fnames:
                remove(oufname)
